import './globals.css'

import HeaderNav from './components/Navigation'

//const inter = Inter({ subsets: ['latin'] })

//export const metadata = {
 // title: 'Create Next App',
  //description: 'Generated by create next app',
//}

export default function RootLayout({ children }) {
  return (
    <html lang="sq">
      <body >
       <HeaderNav/>
        {children}
        <p>Footer</p>
      </body>
    </html>
    
  )
}
